---

- name: oh-my-zsh
  block:
  - name: Install Oh My ZSH via Homebrew
    homebrew:
      name: zsh
      state: present

  - name: Install Oh My ZSH completions via Homebrew
    homebrew:
      name: zsh-completions
      state: present

  tags: oh_my_zsh